source 'https://github.com/kevcodex/kevcodex-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'KevCodexIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MiniNe', '1.3.4'
  pod 'FontAwesome.swift', '1.5.0'

  target 'KevCodexIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
